# -*- coding: utf-8 -*-
"""Calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HiZsUOpLr7Dy4AagJ162ShykrDIczXe2
"""

#keeps running until user types "q"
while True:
    print("Welcome to my first Calculator! Type 'q' to quit :)")
    a = input("Enter first number: ")
    if a == "q":
        print("Goodbye!")
        break
    sign = input("Enter operator: ")
    if sign == "q":
        print("Goodbye!")
        break
    b = input("Enter second number: ")
    if b == "q":
        print("Goodbye!")
        break

    #conversion
    a = float(a)
    b = float(b)

    #logic
    if sign == "+":
        print("Result: ",a + b)
        print("\n")
    elif sign == "-":
        print("Result: ",a - b)
        print("\n")
    elif sign == "*":
        print("Result: ",a * b)
        print("\n")
    elif sign == "/":
        if b == 0:
            print("Error! Division by zero.\n")
        else:
            print("Result: ",a / b)
            print("\n")
    else:
        print("Invalid operator")